/**
 * LECTA AI — HTML Renderer
 * Re-architected with Registry-first & Componentized layout composition (Phase 3).
 * Converts slide JSON data into semantic HTML blocks using atoms and recipes.
 * Works seamlessly in both Node.js (build-time) and browser (runtime CSR).
 */

// Load core atoms and recipes depending on execution environment
let Atoms, Recipes;
if (typeof require !== 'undefined') {
  Atoms = require('../primitives/atoms');
  Recipes = require('../recipes/blocks.recipes');
} else {
  Atoms = window.LectaAtoms || {};
  Recipes = window.LectaRecipes || {};
}

// Map of canonical block types to their corresponding recipe functions
const RECIPE_MAP = {
  'title': Recipes.titleRecipe,
  'splash': Recipes.splashRecipe,
  'bullets': Recipes.bulletsRecipe,
  'accordion': Recipes.accordionRecipe,
  'tabs': Recipes.tabsRecipe,
  'stepper': Recipes.stepperRecipe,
  'cards': Recipes.cardsRecipe,
  'quiz': Recipes.quizRecipe,
  'advanced-quiz': Recipes.advancedQuizRecipe,
  'compare': Recipes.compareRecipe,
  'timeline': Recipes.timelineRecipe,
  'timeline-horizontal': Recipes.timelineHorizontalRecipe,
  'summary': Recipes.summaryRecipe,
  'image': Recipes.imageRecipe,
  'chart': Recipes.chartRecipe,
  'table': Recipes.tableRecipe,
  'bento': Recipes.bentoRecipe,
  'flow': Recipes.flowRecipe,
  'split': Recipes.splitRecipe,
  'math': Recipes.mathRecipe,
  'mermaid': Recipes.mermaidRecipe,
  'video': Recipes.videoRecipe,
  'quote-card': Recipes.quoteCardRecipe,
  'definition-card': Recipes.definitionCardRecipe,
  'analogy': Recipes.analogyRecipe,
  'stats': Recipes.statsRecipe,
  'checklist': Recipes.checklistRecipe,
  'code-diff': Recipes.codeDiffRecipe,
};

/**
 * Main slide rendering function.
 * Composes the slide shell wrapper around the specific block HTML generated by its recipe.
 */
function renderSlideHTML(slide) {
  if (!slide) return '';
  
  const type = slide.type;
  const recipe = RECIPE_MAP[type];

  let innerHTML = '';
  let innerClass = type; // Custom CSS class modifier for slide-inner

  if (recipe) {
    try {
      innerHTML = recipe(slide);
    } catch (err) {
      innerHTML = `<div class="recipe-error">
        <h4>Render Error in block "${type}"</h4>
        <p>${Atoms.esc(err.message)}</p>
      </div>`;
    }
  } else {
    innerHTML = `<div class="recipe-error">
      <h4>Unknown block type</h4>
      <p>No recipe found for block type "${Atoms.esc(type)}".</p>
    </div>`;
  }

  // Composes the final slide section and slide-inner DOM wrapper using the atomic primitive
  return Atoms.slideShell(slide, innerHTML, {
    applyTransitionClass: true,
    innerClass: innerClass,
  });
}

// Export for Node/CommonJS or attach to global window object
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { renderSlideHTML };
} else {
  window.LectaRenderer = { renderSlideHTML };
}
